### ISSUE TITLE
problem for navbar text without href

### ISSUE THREAD

**Issue by ijlyttle** [rstudio/radix#13]
Hi,

Congrats on the CRAN release - I have been lurking, using this for a while; IMHO this is super-useful and looks great!

Using the new CRAN version, I get a weird problem when I put in a navbar `text` item without a corresponding `href` item. My use case is wanting to have headers and `---` separators in the navbar menu.

If I do something like this:

```
navbar:
  right:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
      menu: 
      - text: "header"
      - text: "Thing 1"
        href: index.html
      - text: "Thing 2"
        href: index.html
```

Then the html does not show up properly in the RStudio Preview window, nor at Github pages. However, it does show up locally if I open using a browser.

If I open the JavaScript console from the RStudio Preview window (or from GH pages), it gives me this error:

```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at HTMLAnchorElement.<anonymous> (index.html:1182)
    at Function.each (jquery.min.js:2)
    at m.fn.init.each (jquery.min.js:2)
    at init_common (index.html:1181)
    at init_distill (index.html:875)
    at yh (webcomponents.js:234)
    at webcomponents.js:235
```

Here are links to the working [site](https://ijlyttle.github.io/radixtest/) and [repository](https://github.com/ijlyttle/radixtest).

Here are the links to the failing [site](https://ijlyttle.github.io/radixtestfails/) and [repository](https://github.com/ijlyttle/radixtestfails).
