### ISSUE TITLE
<aside>s that are taller than the paragraph that they are beside use vertical space in the main text

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/radix#39]
Maybe this is intentional too? But I don't think aside that span two paragraphs look bad.

As a quick hack, I added

```css
@media(min-width:768px) {
    aside {
        margin-bottom: -500px;
    }
}
```

I guess this could lead to problems with consecutive asides? But those don't look good, so I'm not too worried.
