### ISSUE TITLE
navbar icon and text not working together

### ISSUE THREAD

**Issue by uhlitz** [rstudio/radix#49]
In navbars, one can only use text or icon to create an item, but not both. depending on the context, either the icon or the text will "win". 

* for top-level items, only the icon is considered
* for top-level menu headers, only the text is considered 
* for menu items, only the icon is considered

YAML example: 

```
navbar:
  left:
    - text: "info"                           # text is disregarded
      icon: fa-list-alt                      # icon is considered
      href: index.html
    - text: "Preprocessing"                  # text is considered
      icon: fa-hourglass-half                # icon is disregarded
      menu:
        - text: "Preprocessing pipeline"     # text is disregarded
          icon: fa-hourglass-half            # icon is considered
          href: pre_pipeline.html
```
