### ISSUE TITLE
XML error when rendering site and article 

### ISSUE THREAD

**Issue by mrjoh3** [rstudio/radix#58]
I am using the Radix to build a  blog site. Yesterday this was working beautifully but today I get an error when I try to build the site. I get the following error but am not sure where to look to fix the issue.

```
Error in node_append_content(x$node, value) : 
  Expecting a single string value: [type=list; extent=0].
Calls: <Anonymous> ... <Anonymous> -> xml_text<-.xml_node -> node_append_content
Execution halted
```

my site YAML is:

```
name: "...-code"
title: "... Code"
description: |
  This is the simple code / script repository for ...
output_dir: "public"
base_url: http://...
navbar:
  title: Small Scripts Repository
  type: default
  left:
  - icon: fa-home
    href: index.html
  - icon: fa-info
    href: about.html
  - text: 'SharePoint'
    href: http://.../Pages/default.aspx
  right:
  - icon: fa-gitlab
    href: http://gitlab...
output: radix::radix_article
```
