### ISSUE TITLE
Date in index page on first build wrong

### ISSUE THREAD

**Issue by dakvid** [rstudio/radix#60]
When trying (unsuccessfully) to reproduce the error in #58, I noticed an odd issue with the date in the index page - the first time the the page was knitted, the date in index.html was out by a day. Possibly this could be due to my timezone (+1300)?

* I created a new radix blog with a post dated Nov 1. The index page listed it as Oct 31.
* I created a new post dated Nov 4. The index page listed it as Nov 3, but updated the first to Nov 1. ([GitHub diff](https://github.com/dakvid/break_radix/commit/34ddbfe9ead4785f7d87fbc31b0bc825fc187b10))
* I created a new post dated Nov 3. The index page listed it as Nov 2, but updated the second to Nov 4. ([GitHub diff](https://github.com/dakvid/break_radix/commit/8b2f4a8c7b25eac1c8c3d6b2da61b4771bdc4695))
* I knitted the third post again, and the index updated it as Nov 3. ([GitHub diff](https://github.com/dakvid/break_radix/commit/39b37be087747053c2515501695dd59384ed3077))

**Comment by malcolmbarrett** [comment]
I'm noticing this issue with `distill_article()`, as well. Using this metadata:

```yaml
---
title: "Untitled"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "April 14, 2021"
output: distill::distill_article
---
```

I get this output:

<img width="730" alt="Screen Shot 2021-04-14 at 10 03 34 AM" src="https://user-images.githubusercontent.com/23123711/114750754-2e2e8800-9d09-11eb-8c38-2061a41751a0.png">

The result is the same using `Sys.Date()`
